proxies:
  - name: "FreedomVPN-SS"
    type: ss
    server: 20.243.177.129
    port: 8388
    cipher: 2022-blake3-aes-256-gcm
    password: kItD4Q4zIWyY5zIaQntKEM7X0Yl9OHLgHVyLFyElzvOrDqMz7JHeF9l3wlWxwS5Ltb2GpGhsc4g1Rxd4uU8dqg==
    udp: true

  - name: "FreedomVPN-V2Ray"
    type: vmess
    server: 20.243.177.129
    port: 10086
    uuid: b12024f0-1c2f-4f91-9efb-ae5553dddf12
    alterId: 0
    cipher: auto
    tls: true
    network: ws
    ws-opts:
      path: /freedom
      headers:
        Host: freedomvpn

  # Example 3rd VPN (VLESS) — replace if needed
  - name: "FreedomVPN-VLESS"
    type: vless
    server: 20.243.177.129
    port: 443
    uuid: 11111111-2222-3333-4444-555555555555
    cipher: none
    tls: true
    network: ws
    ws-opts:
      path: /vless
      headers:
        Host: freedomvpn
